### ISSUE TITLE
Duration of tests/hooks with the same name gets counted only once

### ISSUE THREAD

**Issue by glukki** [msiebuhr/node-mocha-slow-reporter#3]
The case:
```
describe('Test', function () {
  beforeEach(function (done) {
    setTimeout(done, 100);
  });
  it('test 1', function () {});
  it('test 2', function () {});
});
```

Actual:
```
102 ㎳	Whole Suite
102 ㎳	  Test
102 ㎳	    "before each" hook
0 ㎳	    test 1
0 ㎳	    test 2
```

Expected:
```
212 ㎳	Whole Suite
212 ㎳	  Test
211 ㎳	    "before each" hook x2
1 ㎳	    test 2
0 ㎳	    test 1
```

I was really expecting to see a sum of durations for hooks, as I was sure they are slow in my tests.
I have a patch to make output as in Expected, do you find this meaningful?

**Comment by msiebuhr** [comment]
> 211 ㎳	    "before each" hook x2f

Reads like 211 ms two times, giving a total of 422 ms, which is obviously wrong. Perhaps show average and number of runs? Or some more helpful text?

**Comment by glukki** [comment]
Oh, you’re right! I wanted to to make hooks sorted by cumulative duration. How about this format?
```
211 ㎳	    "before each" hook (2 calls)
```
And the `(2 calls)` is an optional text displayed only if there were more than 1 call of that test/hook.

I’ll make a PR to continue there :)
